customers/urls.py
from django.urls import path

from .views import (
    CustomerList,
    CustomerDetail,
    CustomerCreation,
    CustomerUpdate,
    CustomerDelete
)

app_name = 'customers'

urlpatterns = [

    path('customers/', CustomerList.as_view(), name='list'),
    path('customer/<int:pk>/', CustomerDetail.as_view(), name='detail'),
    path('customer/new/', CustomerCreation.as_view(), name='new'),
    path('customer/edit/<int:pk>/', CustomerUpdate.as_view(), name='edit'),
    path('customer/delete/<int:pk>/', CustomerDelete.as_view(), name='delete'),

]

djangoCleaners/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cleaners.urls', 'cleaners_view')),
    path('', include('customers.urls', 'customers_view')),
    path('', include('bookings.urls', 'bookings_view')),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [path('', views.index, name='')]

customers/models.py
from django.db import models


class Customer(models.Model):
    first_name = models.CharField(max_length=100, verbose_name='Имя')
    last_name = models.CharField(max_length=100, verbose_name='Фамилия')
    phone_number = models.CharField(max_length=15, verbose_name="Номер телефона")

customers/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Customer


class CustomerList(ListView):
    model = Customer


class CustomerDetail(DetailView):
    model = Customer


class CustomerCreation(CreateView):
    model = Customer
    success_url = reverse_lazy('customers:list')
    fields = ['first_name', 'last_name', 'phone_number']


class CustomerUpdate(UpdateView):
    model = Customer
    success_url = reverse_lazy('customers:list')
    fields = ['first_name', 'last_name', 'phone_number']


class CustomerDelete(DeleteView):
    model = Customer
    success_url = reverse_lazy('customers:list')

# Create your views here.

customers/templates/customers/customer_detail.html
{% extends 'base.html' %}
{% block title %}
    {{ customer.first_name }} {{ customer.last_name }}
{% endblock %}
{% block content %}
    <h4>{{ customer.first_name }} {{ customer.last_name }}  {{ customer.phone_number }}
     </h4>
    <form method="GET" action="{% url "customers:edit" customer.id %}">
   {% csrf_token %}
        <input type="submit" value="Изменить">
    </form>
    <h1>   </h1>
    <form method="POST" action="{% url "customers:delete" customer.id %}">
   {% csrf_token %}<input type="submit" value="Удалить">
    </form>


{% endblock %}

customers/templates/customers/customer_form.html
{% extends 'base.html' %}
{% block title %}
   {{ title }}
{% endblock %}
{% block content %}


<form  method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Добавить">
</form>
{% endblock %}

customers/templates/customers/customer_list.html
{% extends 'base.html' %}
{% block title %}
   {{ title }}
{% endblock %}
{% block content %}
            {% for customer in object_list %}
            <li>{{ customer.id }} {{ customer.first_name }}  {{ customer.last_name }}  <a href="{% url 'customers:detail' customer.id %}">Детали</a>
            </li>
        {% endfor %}
    <br><a href="{% url 'customers:new' %}">Добавить клиента</a>
{% endblock %}