cleaners/urls.py
from django.urls import path

from .views import (
    CleanerList,
    CleanerDetail,
    CleanerCreation,
    CleanerUpdate,
    CleanerDelete
)

app_name = 'cleaners'

urlpatterns = [

    path('cleaners/', CleanerList.as_view(), name='list'),
    path('cleaner/<int:pk>/', CleanerDetail.as_view(), name='detail'),
    path('cleaner/new/', CleanerCreation.as_view(), name='new'),
    path('cleaner/edit/<int:pk>/', CleanerUpdate.as_view(), name='edit'),
    path('cleaner/delete/<int:pk>/', CleanerDelete.as_view(), name='delete'),

]

djangoCleaners/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cleaners.urls', 'cleaners_view')),
    path('', include('customers.urls', 'customers_view')),
    path('', include('bookings.urls', 'bookings_view')),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [path('', views.index, name='')]

cleaners/models.py
from django.db import models

from cites.models import City


class Cleaner(models.Model):
    first_name = models.CharField(max_length=100, verbose_name='Имя')
    last_name = models.CharField(max_length=100, verbose_name='Фамилия')
    quality_score = models.DecimalField(max_digits=5, decimal_places=2, default=100, verbose_name='Рейтинг')
    number_phone = models.CharField(max_length=15, verbose_name="Номер телефона")
    cities = models.ManyToManyField(City, verbose_name="Города")

    class Meta:
        ordering = ['-quality_score']
        verbose_name = 'Клинер'
        verbose_name_plural = 'Клинеры'

cleaners/views.py
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Cleaner


class CleanerList(ListView):
    model = Cleaner
    paginate_by = 5

    def get_context_data(self):
        context = super().get_context_data()
        context['title'] = 'Список клинеров'
        return context


class CleanerDetail(DetailView):
    model = Cleaner


class CleanerCreation(CreateView):
    model = Cleaner
    success_url = reverse_lazy('cleaners:list')
    fields = ['first_name', 'last_name', 'cities']

    def get_context_data(self):
        context = super().get_context_data()
        context['title'] = 'Добавить клинера'
        return context

    def post(self, request, *args, **kwargs):
        messages.success(self.request, 'Клинер добавлен')
        return super().post(request, *args, **kwargs)

class CleanerUpdate(UpdateView):
    model = Cleaner
    success_url = reverse_lazy('cleaners:list')
    fields = ['first_name', 'last_name', 'cities']

    def post(self, request, *args, **kwargs):
        messages.success(self.request, 'Клинер обновлен')
        return super().post(request, *args, **kwargs)

    def get_context_data(self):
        context = super().get_context_data()
        context['title'] = 'Обновить клинера'
        return context


class CleanerDelete(DeleteView):
    template_name = 'cleaners/cleaner_list.html'
    model = Cleaner
    success_url = reverse_lazy('cleaners:list')

    def post(self, request, *args, **kwargs):
        messages.success(self.request, 'Клинер удален')
        return super().post(request, *args, **kwargs)

cleaners/templates/cleaners/cleaner_detail.html
{% extends 'base.html' %}
{% block title %}
    {{ cleaner.first_name }} {{ cleaner.last_name }}
{% endblock %}
{% block content %}
    <h4>{{ cleaner.first_name }} {{ cleaner.last_name }}  {{ cleaner.quality_score }} {{ cleaner.number_phone }}
        {% for sity in cleaner.cities.all %}
        {{ sity }}
        {% endfor %}
     </h4>
    <form method="GET" action="{% url "cleaners:edit" cleaner.id %}">
   {% csrf_token %}
        <input type="submit" value="Изменить">
    </form>
    <h1>   </h1>
    <form method="POST" action="{% url "cleaners:delete" cleaner.id %}">
   {% csrf_token %}<input type="submit" value="Удалить">
    </form>


{% endblock %}

cleaners/templates/cleaners/cleaner_form.html
{% extends 'base.html' %}
{% block title %}
   {{ title }}
{% endblock %}
{% block content %}


<form  method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Добавить">
</form>
{% endblock %}

cleaners/templates/cleaners/cleaner_list.html
{% extends 'base.html' %}
{% block title %}
   {{ title }}
{% endblock %}
{% block content %}
        {% for cleaner in object_list %}
            <li>{{ cleaner.id }} {{ cleaner.first_name }}  {{ cleaner.last_name }} {{ cleaner.quality_score }}  <a href="{% url 'cleaners:detail' cleaner.id %}">Детали</a>
            </li>
        {% endfor %}
    <br><a href="{% url 'cleaners:new' %}">Добавить клинера</a>
   <span>  {{ massage }}</span>
{% endblock %}