bookings/urls.py
from django.urls import path

from bookings.views import BookingCreate

app_name = 'bookings'

urlpatterns = [
    path('booking/new/', BookingCreate.as_view(), name='new')
]

cleaners/urls.py
from django.urls import path

from .views import (
    CleanerList,
    CleanerDetail,
    CleanerCreation,
    CleanerUpdate,
    CleanerDelete
)

app_name = 'cleaners'

urlpatterns = [

    path('cleaners/', CleanerList.as_view(), name='list'),
    path('cleaner/<int:pk>/', CleanerDetail.as_view(), name='detail'),
    path('cleaner/new/', CleanerCreation.as_view(), name='new'),
    path('cleaner/edit/<int:pk>/', CleanerUpdate.as_view(), name='edit'),
    path('cleaner/delete/<int:pk>/', CleanerDelete.as_view(), name='delete'),

]

customers/urls.py
from django.urls import path

from .views import (
    CustomerList,
    CustomerDetail,
    CustomerCreation,
    CustomerUpdate,
    CustomerDelete
)

app_name = 'customers'

urlpatterns = [

    path('customers/', CustomerList.as_view(), name='list'),
    path('customer/<int:pk>/', CustomerDetail.as_view(), name='detail'),
    path('customer/new/', CustomerCreation.as_view(), name='new'),
    path('customer/edit/<int:pk>/', CustomerUpdate.as_view(), name='edit'),
    path('customer/delete/<int:pk>/', CustomerDelete.as_view(), name='delete'),

]

djangoCleaners/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cleaners.urls', 'cleaners_view')),
    path('', include('customers.urls', 'customers_view')),
    path('', include('bookings.urls', 'bookings_view')),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [path('', views.index, name='')]

templates/base.html
<!DOCTYPE html>
<html class="no-js" lang="">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}{% endblock %} :: MyProject</title>
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--[if lt IE 9]>
            <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
            <script>window.html5 || document.write('<script src="{{ STATIC_URL }}libs/html5shiv.js"><\/script>')</script>
        <![endif]-->
</head>
<body>
<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade
    your browser</a> to improve your experience.</p>
<![endif]-->
<a href="{% url 'cleaners:list' %}">Клинеры</a> |
<a href="{% url 'customers:list' %}">Клиенты</a> |
<a href="{% url 'bookings:new' %}">Оставить заявку</a>
<hr>
{% block content %}{% endblock %}
{% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Предыдущая</a>
              {% endif %}
              <span class="page-current">
                  Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}"><Следующая></Следующая></a>
              {% endif %}
          </span>
        </div>
    {% endif %}
{% endblock %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
   {{ message }}<br>
    {% endfor %}
</ul>
{% endif %}
</body>
</html>